server:
  port: 8787
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/
    username: fsmfppcj  # 사용자 이름
    password: opXwqwWLpezpFQHX6OWFl3mQW1xf0VqH
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
